### ISSUE TITLE
Unable to implement package

### ISSUE THREAD

**Issue by mrgenixus** [K-Society/KSociety.SharpCubeProgrammer#145]
I'm trying to find the gap between the VS Documentation and the documentation for this project. I am unable to implement this project (Thank you, thank you for creating it).

**Error: "K-Society CubeProgrammer implementation not found"**

Full error/stack:
```
System.Exception: K-Society CubeProgrammer implementation not found. ---> System.DllNotFoundException: Unable to load DLL '.\dll\x64\Programmer.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SharpCubeProgrammer.Native.ProgrammerApi.GetUsartList64(IntPtr& usartList)
   at SharpCubeProgrammer.Native.ProgrammerApi.GetUsartList(IntPtr& usartList)
   --- End of inner exception stack trace ---
   at SharpCubeProgrammer.Native.ProgrammerApi.GetUsartList(IntPtr& usartList)
   at SharpCubeProgrammer.CubeProgrammerApi.GetUsartList()
```

**Context**

_MyPackage.UWP.csproj_ (abbridged); has been tried with and without `GeneratePathProperty`

```xml
    <PackageReference Include="KSociety.SharpCubeProgrammer" GeneratePathProperty="true">
      <IncludeAssets>all</IncludeAssets>
      <Version>0.3.20</Version>
    </PackageReference>
```

Please let me know if I can add additional context.

**Comment by maniglia** [comment]
Hello @mrgenixus 
for some reason, not all necessary libraries and files are copied to the output folder.
Could you share a sample project that reproduces this problem please?

**Comment by mrgenixus** [comment]
I realize this took a LONG time, but here is a REPO that demonstrates the issue: https://github.com/mrgenixus/STMDemo

**Comment by mrgenixus** [comment]
Any thoughts on why this example doesn't work

**Comment by maniglia** [comment]
Hi, I found the problem, please try the latest version the _0.4.20_ it should work now.
Please let me know if it works for you.
